---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: argocd
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: petclinic
  template:
    spec:
      containers:
        - image: 05021997/petclinic-gitops:main-96f5a59e6efa9e685077017669a7889c55d11049
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: argocd
  labels:
    app: petclinic
spec:
  replicas: 5
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: workload
          image: 05021997/petclinic-gitops:main-96f5a59e6efa9e685077017669a7889c55d11049
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres
            - name: SERVICE_BINDING_ROOT
              value: /bindings
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true
                }
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /livez
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          volumeMounts:
            - mountPath: /bindings/secret
              name: binding
              readOnly: true
      volumes:
        - name: binding
          projected:
            sources:
              - secret:
                  name: demo-db
