# This workflow builds a Java project with Maven, caches dependencies, and pushes a Docker image to Docker Hub.
# For more information, see: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-maven

name: Java CI with Maven and Docker Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: maven

      # Build the project with Maven
      - name: Build with Maven Wrapper
        run: ./mvnw -B verify

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t 05021997/petclinic-gitops:$GITHUB_SHA .
      
      # Push the Docker image
      - name: Push Docker Image to Docker Hub
        run: |
          docker push 05021997/petclinic-gitops:$GITHUB_SHA

      - name: Update manifest file
        run: |
          # Assuming you have a manifest file named k8s.yaml
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@gmail.com"
          yq eval '.spec.template.spec.containers[0].image = 05021997/petclinic-gitops:$GITHUB_SHA' -i k8s/petclinic.yml

          git pull
          git add .
                    
          git commit -m "updating newer image"
          git push --set-upstream origin main  
